name: eatall
description: eatall

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  visibility_detector: ^0.3.3
  bloc: ^8.1.1
  go_router: ^6.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  sign_in_with_apple: ^4.3.0
  kakao_flutter_sdk: ^1.4.2
  flutter_naver_login: ^1.7.0
  image_picker: ^0.8.7
  web_socket_channel: ^2.3.0
  firebase_storage: ^11.1.0
  flutter_swiper_null_safety: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  video_compress: ^3.1.2
  better_player: ^0.0.83
  video_thumbnail: ^0.5.3
  shared_preferences: ^2.1.0
  carousel_slider: ^4.2.1
  camera: ^0.10.4
  path_provider: ^2.0.14
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
